//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTime
    {
        public int timeid { get; set; }
        public string username { get; set; }
        public string cDay { get; set; }
        public string cTime { get; set; }
        public string InOROut { get; set; }
        public System.DateTime cDate { get; set; }
    }
}
